#!/bin/bash
# vim: set ft=sh:

get_dir() {
        local script_path; script_path=$(readlink -f "$0")
        local script_dir; script_dir=$(dirname "$script_path")
        echo "$script_dir"
}

WD=$(get_dir)

_init_hg() {
        echo "### $1 hg ###"
        cd "$WD/hg" || return $?
        hg clone "http://hg.tryton.org/$1"
        echo
}

init_hg() {
        [ -e "$WD/hg" ] && echo "hg already initialized" && return 1
        mkdir "$WD/hg" || return $?
        local repo
        while read repo
        do
                (_init_hg "$repo")
        done < "$WD/repos"
        while read repo
        do
                (_init_hg "modules/$repo")
        done < "$WD/modules"
}

_init_git() {
        echo "### $1 git ###"
        mkdir "$WD/git/$1" && cd "$_" || return 1
        git init
        git remote add origin "git@github.com:coopengo/$1.git"
        echo
}

init_git() {
        [ -e "$WD/git" ] && echo "git already initialized" && return 1
        mkdir "$WD/git" || return $?
        local repo
        while read repo
        do
                (_init_git "$repo")
        done < "$WD/repos"
        while read repo
        do
                (_init_git "$repo")
        done < "$WD/modules"

}

main() {
        if [ -z "$1" ]
        then
                init_hg || return $?
                init_git || return $?
        else
                [ $# -ne 2 ] && echo "bad params number" && return 1
                ("_init_$1" "$2")
                return $?
        fi
}

main "$@"
