#!/bin/bash
# vim: set ft=sh:

get_dir() {
        local script_path; script_path=$(readlink -f "$0")
        local script_dir; script_dir=$(dirname "$script_path")
        echo "$script_dir"
}

WD=$(get_dir)

init_hg() {
        [ -e "$WD/hg" ] && echo "hg already initialized" && return 1
        mkdir "$WD/hg" && cd "$_" || return 1
        while read repo
        do
                hg clone "http://hg.tryton.org/$repo"
        done < "$WD/repos"
        while read repo
        do
                hg clone "http://hg.tryton.org/modules/$repo"
        done < "$WD/modules"
}

_init_git() {
        cd "$WD/git/$1"
        git init
}

init_git() {
        [ -e "$WD/git" ] && echo "git already initialized" && return 1
        mkdir "$WD/git" && cd "$_" || return 1
        while read repo
        do
                mkdir "$repo"
                (_init_git "$repo")
        done < "$WD/repos"
        while read repo
        do
                mkdir "$repo"
                (_init_git "$repo")
        done < "$WD/modules"

}

init() {
        init_hg || return $?
        init_git || return $?
}

init "$@"
